# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtGui, QtWidgets, QtCore
from PyQt5.QtWidgets import QApplication, QDialog, QMainWindow

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 272)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 351, 61))
        self.groupBox.setObjectName("groupBox")
        self.edt_file = QtWidgets.QTextEdit(self.groupBox)
        self.edt_file.setGeometry(QtCore.QRect(10, 20, 231, 27))
        self.edt_file.setObjectName("edt_file")
        self.btn_find  = QtWidgets.QPushButton(self.groupBox)
        self.btn_find.setGeometry(QtCore.QRect(240, 20, 31, 28))
        self.btn_find.setObjectName("btn_find")
        self.btn_load = QtWidgets.QPushButton(self.groupBox)
        self.btn_load.setGeometry(QtCore.QRect(270, 20, 71, 28))
        self.btn_load.setObjectName("btn_load")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(9, 119, 351, 71))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_play = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_play.setGeometry(QtCore.QRect(10, 20, 51, 41))
        self.btn_play.setObjectName("btn_play")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(76, 19, 51, 21))
        self.label_5.setObjectName("label_5")
        self.edt_frame = QtWidgets.QLineEdit(self.groupBox_3)
        self.edt_frame.setGeometry(QtCore.QRect(70, 40, 51, 18))
        self.edt_frame.setObjectName("edt_frame")
        self.btn_play.raise_()
        self.label_5.raise_()
        self.edt_frame.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 59, 351, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(11, 11, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(11, 37, 21, 16))
        self.label.setObjectName("label")
        self.edt_row = QtWidgets.QLineEdit(self.groupBox_2)
        self.edt_row.setEnabled(False)
        self.edt_row.setGeometry(QtCore.QRect(38, 11, 63, 20))
        self.edt_row.setObjectName("edt_row")
        self.edt_col = QtWidgets.QLineEdit(self.groupBox_2)
        self.edt_col.setEnabled(False)
        self.edt_col.setGeometry(QtCore.QRect(38, 37, 63, 20))
        self.edt_col.setObjectName("edt_col")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(107, 11, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(107, 37, 16, 16))
        self.label_4.setObjectName("label_4")
        self.edt_ini = QtWidgets.QLineEdit(self.groupBox_2)
        self.edt_ini.setEnabled(False)
        self.edt_ini.setGeometry(QtCore.QRect(127, 11, 63, 20))
        self.edt_ini.setObjectName("edt_ini")
        self.edt_fin = QtWidgets.QLineEdit(self.groupBox_2)
        self.edt_fin.setEnabled(False)
        self.edt_fin.setGeometry(QtCore.QRect(127, 37, 63, 20))
        self.edt_fin.setObjectName("edt_fin")
        self.horizontalSlider = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(9, 200, 351, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 373, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuration File"))
        self.btn_find.setText(_translate("MainWindow", "..."))
        self.btn_load.setText(_translate("MainWindow", "Load"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Events"))
        self.btn_play.setText(_translate("MainWindow", ">"))
        self.label_5.setText(_translate("MainWindow", "Frame"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Video"))
        self.label_2.setText(_translate("MainWindow", "Col"))
        self.label.setText(_translate("MainWindow", "Row"))
        self.label_3.setText(_translate("MainWindow", "Ini"))
        self.label_4.setText(_translate("MainWindow", "Fin"))

